### ISSUE TITLE
home assistant version 2024.12.3 breaks integration

### ISSUE THREAD

**Issue by RMHogervorst** [cyberjunky/home-assistant-shell_recharge#76]
## System Information

version | core-2024.12.3
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 5.15.0-126-generic
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4945
Installed Version | 2.0.1
Stage | running
Available Repositories | 1546
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 15
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 6, 2024 at 11:19
-- | --
current_recorder_run | December 15, 2024 at 13:34
estimated_db_size | 1330.48 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/cyberjunky/home-assistant-shell_recharge/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The integration cannot find the package shellrecharge. 

I believe the move to python 3.13 or package manager could be the issue?

```
2024-12-15 13:34:14.911 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'shell_recharge': Unable to import component: No module named 'shellrecharge'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/shell_recharge/__init__.py", line 7, in <module>
    import shellrecharge
ModuleNotFoundError: No module named 'shellrecharge'
```

### Reproduction steps

1. home assistant 2024.11.x and install shellrecharge (this works fine)
2. upgrade home assistant to 2024.12.x
3. ... profit?
...

### Debug logs

```text
-
```

### Diagnostics dump

-

**Comment by RMHogervorst** [comment]
https://community.home-assistant.io/t/python-libraries-missing-in-2024-12-0/805633

**Comment by RMHogervorst** [comment]
re-installation does not work ( I had to add your repo to hacs manually because it is no longer in hacs see #75 )

**Comment by cyberjunky** [comment]
I will have a look, maybe a too strict dependency in the pkg...

**Comment by cyberjunky** [comment]
I cannot reproduce it, it's running fine here on: 
![image](https://github.com/user-attachments/assets/a9cc0e25-997e-41d1-820c-e9b67fbe1d76)
![image](https://github.com/user-attachments/assets/5f308cb7-894a-491d-a2f0-25158d6cb33c)

Requirement of shellrecharge is python>=3.10 so thats not it either, what type of home assistant install do you use?

**Comment by RMHogervorst** [comment]
I use a docker container, 2024.12.3

**Comment by RMHogervorst** [comment]
I have removed the extension, including the points I created. removed it from hacs, restarted home assistant. re-added the repo to HACS, downloaded shell recharge, restarted home assistant tried to install the integration and still get:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

**Comment by RMHogervorst** [comment]
Here I copy some things from the debug json that contain shell

```json
"shell_recharge": {
      "documentation": "https://github.com/cyberjunky/home-assistant-shell_recharge",
      "version": "0.1.12",
      "requirements": [
        "shellrecharge==0.1.18"
      ]
    },
```

```json
{
        "data": {
          "archived": false,
          "authors": [
            "@cyberjunky"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "The Shell Recharge integration allows you to expose data from EV chargers listed on shellrecharge.com to Home Assistant.",
          "domain": "shell_recharge",
          "downloads": 0,
          "etag_repository": "W/\"142f93d977761cf4500b675c1059d240a3c7eb6e6a1e97e4b29714a698004457\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "cyberjunky/home-assistant-shell_recharge",
          "hide": false,
          "has_issues": true,
          "id": "738508440",
          "installed_commit": "f5fd434",
          "installed_version": "0.1.12",
          "installed": true,
          "last_commit": "f5fd434",
          "last_updated": "2024-12-23T11:39:24Z",
          "last_version": "0.1.12",
          "manifest_name": "Shell Recharge",
          "new": false,
          "open_issues": 0,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 4,
          "topics": [
            "electrical-vehicle-charging-station",
            "electrical-vehicles"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": "1.34.0",
          "hide_default_branch": false,
          "homeassistant": "2024.11.0",
          "manifest": {
            "hacs": "1.34.0",
            "homeassistant": "2024.11.0",
            "name": "Shell Recharge",
            "render_readme": true
          },
          "name": "Shell Recharge",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/shell_recharge",
          "local": "/config/custom_components/shell_recharge",
          "remote": "custom_components"
        }
      }
```

**Comment by RMHogervorst** [comment]
I upgraded home assistant to 2024.12.5 but still no dice

**Comment by RMHogervorst** [comment]
I don't know what goes wrong, but I executed into the home assistant container and installed the shell recharge package with pip3 and now the extension works again, I can add the charging points again.

**Comment by rubenbe** [comment]
Same problem with docker container 2024.12.0. First install of this integration.

I did find this error in the logfile:

ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration shell_recharge: No module named 'shellrecharge'

**Comment by cyberjunky** [comment]
@rubenbe I noticed too that this issue is all over the place on the forum, I wonder why that isn't working, pip3 install on a docker installation, is this by design, technically limited or a bug?

**Comment by cyberjunky** [comment]
Knowing it's a HA developers requirement to put any api calls in a separate python module, this is even more strange.

**Comment by cyberjunky** [comment]
Is this still an issue with latest version of HA and others?

**Comment by rubenbe** [comment]
Works fine for me (HA 2025.2.0 with 0.1.12)
